export interface LocationGroup {
  label: string
  locations: string[]
}

export const UK_LOCATION_GROUPS: LocationGroup[] = [
  {
    label: 'Airports',
    locations: [
      'Heathrow Airport (LHR)',
      'Gatwick Airport (LGW)',
      'Stansted Airport (STN)',
      'Luton Airport (LTN)',
      'City Airport (LCY)',
      'Manchester Airport (MAN)',
      'Birmingham Airport (BHX)',
      'Edinburgh Airport (EDI)',
      'Glasgow Airport (GLA)',
      'Bristol Airport (BRS)',
      'Leeds Bradford Airport (LBA)',
      'Liverpool Airport (LPL)',
      'Newcastle Airport (NCL)',
      'East Midlands Airport (EMA)',
      'Southampton Airport (SOU)',
      'Cardiff Airport (CWL)',
      'Aberdeen Airport (ABZ)',
      'Belfast International (BFS)',
      'George Best Belfast City (BHD)',
      'Southend Airport (SEN)',
    ],
  },
  {
    label: 'London',
    locations: [
      'Central London',
      'Canary Wharf',
      'Heathrow',
      'Gatwick',
      'Stansted',
      'London City',
      'Croydon',
      'Greenwich',
      'Hackney',
      'Hammersmith',
      'Islington',
      'Kensington',
      'Kingston upon Thames',
      'Lewisham',
      'Paddington',
      'Richmond',
      'Shoreditch',
      'Stratford',
      'Wembley',
      'Wimbledon',
    ],
  },
  {
    label: 'South East England',
    locations: [
      'Brighton',
      'Canterbury',
      'Chatham',
      'Chichester',
      'Crawley',
      'Dartford',
      'Dover',
      'Eastbourne',
      'Folkestone',
      'Gillingham',
      'Guildford',
      'Hastings',
      'Maidstone',
      'Margate',
      'Milton Keynes',
      'Oxford',
      'Reading',
      'Slough',
      'Southampton',
      'Worthing',
    ],
  },
  {
    label: 'South West England',
    locations: [
      'Bath',
      'Bournemouth',
      'Bristol',
      'Cheltenham',
      'Exeter',
      'Gloucester',
      'Plymouth',
      'Poole',
      'Salisbury',
      'Swindon',
      'Taunton',
      'Torquay',
      'Truro',
    ],
  },
  {
    label: 'East of England',
    locations: [
      'Cambridge',
      'Chelmsford',
      'Colchester',
      'Ipswich',
      'Luton',
      'Norwich',
      'Peterborough',
      'Southend-on-Sea',
      'St Albans',
      'Stevenage',
      'Watford',
    ],
  },
  {
    label: 'East Midlands',
    locations: [
      'Derby',
      'Leicester',
      'Lincoln',
      'Northampton',
      'Nottingham',
      'Shrewsbury',
      'Stoke-on-Trent',
      'Telford',
    ],
  },
  {
    label: 'West Midlands',
    locations: [
      'Birmingham',
      'Coventry',
      'Hereford',
      'Solihull',
      'Wolverhampton',
      'Worcester',
    ],
  },
  {
    label: 'North West England',
    locations: [
      'Blackburn',
      'Blackpool',
      'Bolton',
      'Burnley',
      'Chester',
      'Crewe',
      'Lancaster',
      'Liverpool',
      'Manchester',
      'Oldham',
      'Preston',
      'Rochdale',
      'Salford',
      'Warrington',
      'Wigan',
    ],
  },
  {
    label: 'Yorkshire & Humber',
    locations: [
      'Barnsley',
      'Bradford',
      'Doncaster',
      'Grimsby',
      'Harrogate',
      'Hull',
      'Leeds',
      'Rotherham',
      'Scarborough',
      'Sheffield',
      'Wakefield',
      'York',
    ],
  },
  {
    label: 'North East England',
    locations: [
      'Carlisle',
      'Durham',
      'Gateshead',
      'Middlesbrough',
      'Newcastle upon Tyne',
      'Sunderland',
    ],
  },
  {
    label: 'Scotland',
    locations: [
      'Aberdeen',
      'Dundee',
      'Edinburgh',
      'Glasgow',
      'Inverness',
      'Perth',
      'St Andrews',
      'Stirling',
    ],
  },
  {
    label: 'Wales',
    locations: [
      'Bangor',
      'Cardiff',
      'Newport',
      'Swansea',
      'Wrexham',
    ],
  },
  {
    label: 'Northern Ireland',
    locations: [
      'Belfast',
      'Londonderry',
      'Lisburn',
      'Newry',
    ],
  },
]

export const UK_LOCATIONS = UK_LOCATION_GROUPS.flatMap((g) => g.locations)
